# Generated by Django 3.1.7 on 2021-04-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210417_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='loginapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='posted_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_for', to='loginapp.user'),
            preserve_default=False,
        ),
    ]
